# https://taskfile.dev

version: '3'

includes:
  test: ./tests/Taskfile.yml

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task -l
    silent: true

  check:
    desc: "Run pre-commit hooks"
    cmds:
      - pre-commit run -a

  pre-commit:
    cmds:
      - pre-commit install
    sources:
      - .git/hooks/pre-commit
      - .pre-commit-config.yaml
    generates:
      - .git/hooks/pre-commit
    method: checksum

  pre-commit-setup:
    preconditions:
      - sh: "command -v pre-commit"
        msg: "Pre-commit not found (https://pre-commit.com)"
    cmds:
      - echo "All requirements met"

  setup:
    desc: Bootstrap dev environment
    preconditions:
      - sh: "[ $(python3 --version | cut -d ' ' -f 2 | awk -F'.' '{print ($2 > 6) }') = 1 ]"
        msg: "Required python version not found (>=3.6)"
    cmds:
      - task: pre-commit-setup
      - task: pre-commit

  test:
    desc: Alias for test:all
    cmds:
      - task: test:all
